### ISSUE TITLE
Please make a BOM

### ISSUE THREAD

**Issue by amoore2600** [Redherring32/OpenNES#1]
Please make a BOM.

This looks like a fun project. If there was an easy BOM I would buy all the parts and give it a go. 

I would even be fun to with an RGB mod.

**Comment by amoore2600** [comment]
Never mind I found the BOM.

**Comment by ekirchman** [comment]
@amoore2600 Where did you find the BOM?

**Comment by Redherring32** [comment]
It's under the release page: 
https://github.com/Redherring32/OpenTendo/releases/tag/V1.1
It's the "BOM.CSV" file.
