### ISSUE TITLE
BOM Errors and Unused silk screen markings disappeared between 1.1 and 1.2.

### ISSUE THREAD

**Issue by muramasatheninja** [Redherring32/OpenNES#10]
On V1.1 The following are marked 'unused' R14, R16, C6 and C7, but not on V1.2 

TC1, RA2, and R14 are also missing from the BOM.

C4, C6, C7, C21, and C44 are all 220pf. C21 is using a different wider footprint then the others. This can probably be consolidated.

On the schematic and the board C20, C43, and C45 are listed as 51pf. In the BOM though they are listed as 56pf (K560J15C0GF5TL2).

It might also make sense to mark these on the BOM somehow so people know they don't actually need to obtain them.

**Comment by Redherring32** [comment]
All issues should now be resolved.
Unused parts, and parts that can't be obtained from normal suppliers have been removed from the BOM, and footprint width inconsistencies have been resolved.

Regarding the inconsistency of C20, C43, and C45, their rated value on the PCB can't be easily obtained, so the BOM substitutes another value which is within required tolerances. (56pF)
