### ISSUE TITLE
6116SA15TPG alternative

### ISSUE THREAD

**Issue by maci0** [Redherring32/OpenNES#11]
CY7C128A seems to be a cheaper alternative to the 6116SA15TPG $69SGD vs $5.54SGD for 10.
Looking at the datasheet they seem to be pin and voltage compatible.
Biggest difference I could see is that the CY7C128A is not rated for industrial and military grade ambient temperatures.
I don't expect any OpenTendos to be used on the wing of an airplane mid-flight, so it should be fine.

**Comment by Redherring32** [comment]
If you can confirm they work as a replacement I'd gladly update the BOM. :)

**Comment by Scyllinice** [comment]
Sorry to bump this a bit, but it looks like the 6116SA15TPG is no longer available at Mouser or Digikey. An available alternative would be nice to have if this situation doesn't change.

The NESessity board uses `AS6C62256-55PCN` which is 32Kx8 and a 28 pin DIP, so it definitely won't physically fit even if it would work as is.
