### ISSUE TITLE
[Question] Power module replacement

### ISSUE THREAD

**Issue by Baktus79** [Redherring32/OpenNES#12]
I have searched everywhere for a power/AV module either as a used one or a board that I can print myself, but it is completely impossible to find. There are some boards out there, but they are not complete or do not work without additional high def expansion cards.

Do you know about something that works with standard mono and composite? Or maybe you made something yourself?

**Comment by Redherring32** [comment]
I have designed a replacement, it just needs testing before I open source it.

**Comment by Baktus79** [comment]
Thank you for your answer! Amazing work you have done with Opentendo! Then I will wait until you make the power module available.

**Comment by cacois** [comment]
Sorry to resurrect a closed thread @Redherring32, but I'm curious - was the power module you mentioned ever completed?
