### ISSUE TITLE
C20 value inconsistency between schematic, pcb and bom

### ISSUE THREAD

**Issue by Kjubyte** [Redherring32/OpenNES#17]
Hi,
in d530f0018b1901474343302d69b92cd2f602043a you changed C20 from 51pF to 220pF in all schematics, but the pcb silk screen and bom still shows 51pF. I guess, this should be also changed to 220pF?

**Comment by Redherring32** [comment]
Yes, I have checked my work again to double check, and it being 51pF was an error, it should be 220pF. :)
I thought I had changed the silkscreen to reflect this fix but I guess it slipped through the cracks.

**Comment by Redherring32** [comment]
Fixed in https://github.com/Redherring32/OpenTendo/commit/5e7f66dc437d01216686a1833f801d3e9a8801c2

(BOM will also be updated when possible)
