### ISSUE TITLE
RA2 substitute

### ISSUE THREAD

**Issue by gabrielBitts** [Redherring32/OpenNES#19]
I accidentally broke the original 5 pin 6.8kx4 resister array from the original board, but I'm not finding this component anywhere over the internet.
There is any substitute of this component that I can use?

**Comment by Redherring32** [comment]
This should work as a drop in replacement, will add it to the BOM in the next version.

https://www.mouser.com/ProductDetail/Bourns/4605X-101-682LF?qs=9G919%252BqIayZU2i1HieWILw%3D%3D
