### ISSUE TITLE
some KiCad symbols missing

### ISSUE THREAD

**Issue by mluna0101** [Redherring32/OpenNES#2]
The component FC1 is missing it's symbol. Motherboard-rescue:Ferrite_Core-Schematic not found.

As well as DA1, DA2, DA3 and D4. "Schematic" library not found.

**Comment by Redherring32** [comment]
The issue should be fixed now in the latest commit (A fresh clone should open the schematic without any setup.), it was caused by lack of relative paths, and the latest schematic library not being commited.

**Comment by mluna0101** [comment]
See no issues so far. Thanks you!
