### ISSUE TITLE
6116SA15TPG replacement

### ISSUE THREAD

**Issue by ceddr69** [Redherring32/OpenNES#20]
Hello,

Can the 6116SA15TPG be replaced with the original Nes Ram ? It's very hard (and expensive) to find now ... I have sanyo lc3517bs-15 available on a damaged nes board.

Thanks in advance,

**Comment by jparks1980** [comment]
Yes I am also having difficulty locating 6116SA15TPG.  Nobody seems to have any.  I see there are other chips of the same 6116 type but am unsure if they are compatible.  Has anyone found an alternative to this or a place that can still source the 6116SA15TPG?

Also wondering if the 20ns version of the 6116 would work?  They are still available.

Update:

Im unsure but I suspect the 6116SA15SOG8 is the same exact chip as the 6116SA15TPG except the 6116SA15SOG8 is SMD and the other is through the board. Basically a more modern version. I think designers are moving away from through the board components. If 6116SA15SOG8 is the same, an adapter board could definitely be made. Of course I am only guessing at this point.

**Comment by jparks1980** [comment]
Im unsure but I suspect the 6116SA15SOG8 is the same exact chip as the 6116SA15TPG except the 6116SA15SOG8 is SMD and the other is through the board.  Basically a more modern version.  I think designers are moving away from through the board components.  If 6116SA15SOG8 is the same, an adapter board could definitely be made.  Of course I am only guessing at this point.

**Comment by Redherring32** [comment]
The RAM from an original OEM motherboard can be used on OpenTendo, as well as any of the chips. 
No issues at all with doing that. :)

I haven't had much time to look into it myself, but if someone finds an active part number for RAM I'd be happy to add it to the BOM.
