### ISSUE TITLE
BOM could highlight X1 is NTSC/PAL dependent

### ISSUE THREAD

**Issue by vb216** [Redherring32/OpenNES#3]
Hi,

Trying to build a NES from scratch based on your board (thanks for putting that out there), and getting a pretty broken video signal on power on. I saw your comment on nesdev (https://forums.nesdev.com/viewtopic.php?f=9&t=21018&hilit=opentendo&start=15) that you were working on an updated BOM, and after digging into it some more I suspect part of my problem might be I've gone for the PAL UA6527P and UA6528P chips, and didn't realise I should adjust the clock to match. 

If you're releasing a new BOM sometime, could be worth marking that X1 should match the PAL/NTSC choice? Unfortunately looks harder to find a 26.601712mhz clock so my PAL choice doesn't seem such a great move.

You've probably spotted it already, but I think there's a 20k resistor listed in the BOM for R8 when it should be a 12k too, from the board marking?

Thanks again, has been fun building it so far!

**Comment by Redherring32** [comment]
Hi!
Thank you for your feedback. 

Regarding the BOM yes I am trying to put out a fixed BOM, though I haven't had as much time to work on this type of thing as of late, I'm not sure how the BOM errors occured honestly, the BOM was generated from my schematic, which is correct, I suspect some sort of software bug was at play

As for stating the regional dependence in the BOM; that's not really practical/feasible, however I can put it in the release description. 

Thank you for your interest in my work!

**Comment by vb216** [comment]
Cool that all makes sense, yeah as you say probably just needs a line where you're talking about sourcing the CPU+PPU to match the X1 sourced. In hindsight kind of obvious I guess, but its an interesting learning curve!
Thanks again for the work on the board and making it an open source contribution.

**Comment by vb216** [comment]
Thanks for the new commits
