### ISSUE TITLE
Recommended Printer for Board?

### ISSUE THREAD

**Issue by dustinschultz** [Redherring32/OpenNES#4]
Hi,

This isn't an issue but I didn't have any other way to contact you. 

Do you have a recommended place to print the PCB? I know there are several out there but looking for a recommendation (e.g. where you've printed it before) so it will be printed well.

Thanks,
Dustin

**Comment by Redherring32** [comment]
I personally go with JLCPCB as they're cheap and high quality, though I think some people use PCBWay for it as well.  

For future reference if anyone else sees this; I can also be contacted through Twitter: "@ redherring32" and I also have an email in the "CONTRIB.txt" file in the repo. 

Thanks for your interest in my work!
