### ISSUE TITLE
R13 - Wrong value ?

### ISSUE THREAD

**Issue by pep3175** [Redherring32/OpenNES#5]
I wasn't able to boot up any game until I change R13. On the schematics and on the board silkscreen you mention 1.2k for R13.

On my original board I have 150k for R13.

I managed to boot it up with 150k.

**Comment by pep3175** [comment]
I just checked your picture : https://camo.githubusercontent.com/07663c0c9fcb0e95c5505d66159466bb3d674cb9014f4548a6f51fd7f6c98c54/68747470733a2f2f692e696d6775722e636f6d2f6e515036426f4d2e6a7067

![image](https://user-images.githubusercontent.com/59727461/107976360-b4ed1000-6fb9-11eb-8f73-55ecf460e2c9.png)

It seems you also use a 150k resistor for R13

**Comment by Redherring32** [comment]
I re-checked everything and you are correct, that is indeed supposed to be 150K.
I have put up a commit that fixes that, and I have updated the schematic/BOM/gerbers in the V1.2 release to fix this as well.

Thank you for bringing this to my attention!
