### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by johnniec30** [Redherring32/OpenNES#6]
Not to distract from the Awesome work you've done with this board.   I was curious if you have thought of doing this for the NES-101 and other JP variations of the board to allow for restoration of those as well.

**Comment by Redherring32** [comment]
I've been keeping it on the down low, but may as well say it here since it's gonna be public at some point anyway; I am actively working on the NES-101 which will be public on my GitHub once I am finished.

I can't however speak of any future plans for reverse engineering. :)
