### ISSUE TITLE
Cartridge Connector Footprint Flipped

### ISSUE THREAD

**Issue by ryancole38** [Redherring32/OpenNES#8]
Hi, first of all thanks for all of your hard work!  I'm using the footprint for the cartridge connector in a project, and when laying out the PCB, I noticed that the footprint for the cartridge connector seems to have one side reversed.  According to [the nesdev wiki page](https://wiki.nesdev.com/w/index.php/Cartridge_connector), pin 1 should be on the other side from pin 37 and pin 36 should be on the other side from pin 72.  As it currently stands, the footprint is aligned such that pins 36 and 37 are directly on the opposite side from each other.  Also, pin 38 seems to be labeled 28 (although this could just be an issue on my end).

I thought it might just be a difference in numbering, but the the CIC connections are supposed to be right across from each other, but on my PCB they are on opposite halves of the board.

It's entirely possible that I'm simply using the footprint wrong since I'm very new to Kicad, but if this is the case I can update the footprint with my fix.

**Comment by Redherring32** [comment]
I can confirm that the footprint is correct on my end: 
![image](https://user-images.githubusercontent.com/47650594/112730876-06b27f80-8f02-11eb-9653-69bec1dfe919.png)
![image](https://user-images.githubusercontent.com/47650594/112730883-0fa35100-8f02-11eb-968b-16f025306758.png)

**Comment by ryancole38** [comment]
Interesting- that's what I expect to see as well.  Let me do a fresh pull and start up a new project to see if I can duplicate what my issue was.

**Comment by ryancole38** [comment]
Here's what I see if I open up the footprint in the footprint editor:

<img width="1427" alt="EdgeFootprint1" src="https://user-images.githubusercontent.com/37026955/112732721-07eba880-8f12-11eb-8044-75ee09d3e333.png">

<img width="1328" alt="EdgeFootprint2" src="https://user-images.githubusercontent.com/37026955/112732723-0b7f2f80-8f12-11eb-9a98-6d368805dc73.png">

**Comment by Redherring32** [comment]
Just did a fresh clone and it's still correct on my end:
![image](https://user-images.githubusercontent.com/47650594/112733611-0371c080-8f0f-11eb-8518-84f9bf8a4b7c.png)
![image](https://user-images.githubusercontent.com/47650594/112733618-08367480-8f0f-11eb-8244-52830ee7893c.png)

**Comment by ryancole38** [comment]
Huh.  I still haven't figured out why it shows up the way it does for me.  Probably user error.  Even looking at the footprint that the motherboard references it shows up wrong, but the motherboard PCB shows up correctly.  I'll close the issue and update if I ever figure out what I did.  Thanks for double checking!
