### ISSUE TITLE
PAL Crystal (X1)

### ISSUE THREAD

**Issue by ray73864** [Redherring32/OpenNES#9]
How exact does the frequency have to be for the PAL crystal? 
Does it have to be exactly 26.601712MHz, or can it be slightly different?

Besides extracting the existing one out of one of the NES PAL consoles that I have (I have PAL Mattel NES consoles as I am in Australia), I can't find any place that actually sells that particular frequency.

Have looked at Digi-Key, Mouser, RS-Components, Element14, and eBay, and the closest I can come is 26MHz or 26.64MHz, with some varying numbers in the middle, but nothing bang on.

Well, except for AliExpress, where they come in lots of 10.

**Comment by Redherring32** [comment]
It has to be pretty darn exact, however whether ~0.04-0.06MHz is too much higher idk. 
You run the risk of AliExpress crystals being off by more anyway I suppose?

**Comment by retrorepair** [comment]
Speaking from experience, yes, it does have to be exact and frankly, they're cheap enough on Aliexpress that it's worth buying the lot of 10 (because you probably won't find them elsewhere).
